-- Seed: Bill of Lading standardized template with allowed key-value pairs.
INSERT INTO standardized_templates (name, slug, description, key_value_pairs, is_active)
VALUES (
  'Bill of Lading',
  'bill-of-lading',
  'Standard fields for a Bill of Lading; only these keys can be used when creating a template from this standard.',
  '[
    {"key":"shipper","label":"Shipper"},
    {"key":"consignee","label":"Consignee"},
    {"key":"notify_party","label":"Notify Party"},
    {"key":"place_of_receipt","label":"Place of Receipt"},
    {"key":"ocean_vessel","label":"Ocean Vessel"},
    {"key":"port_of_loading","label":"Port of Loading"},
    {"key":"port_of_discharge","label":"Port of Discharge"},
    {"key":"place_of_delivery","label":"Place of Delivery"},
    {"key":"bill_of_lading_no","label":"Bill of Lading No"},
    {"key":"carrier_reference","label":"Carrier''s Reference"},
    {"key":"shipper_reference","label":"Shipper''s Reference"},
    {"key":"pages","label":"Pages"},
    {"key":"description_of_goods","label":"Description of Goods"},
    {"key":"gross_weight","label":"Gross Weight"},
    {"key":"gross_weight_unit","label":"Gross Weight Unit"},
    {"key":"measurement","label":"Measurement"},
    {"key":"measurement_unit","label":"Measurement Unit"},
    {"key":"freight_charges","label":"Freight Charges"},
    {"key":"pre_carriage_by","label":"Pre-carriage By"},
    {"key":"shipped_on_board_date","label":"Shipped on Board Date"},
    {"key":"number_of_containers","label":"Number of Containers"},
    {"key":"container_seal_numbers","label":"Container/Seal Numbers"},
    {"key":"declared_value","label":"Declared Value"},
    {"key":"freight_payable_at","label":"Freight Payable At"},
    {"key":"number_of_originals","label":"Number of Originals"},
    {"key":"place_of_issue","label":"Place of Issue"},
    {"key":"date_of_issue","label":"Date of Issue"},
    {"key":"carrier_name","label":"Carrier Name"},
    {"key":"authorized_signatory","label":"Name of Authorized Signatory"},
    {"key":"signature","label":"Signature"},
    {"key":"marks_and_numbers","label":"Marks and Numbers"},
    {"key":"package_quantity","label":"No. of Packages"},
    {"key":"package_type","label":"Kind of Packages"},
    {"key":"additional_notify_party","label":"Additional Notify Party"},
    {"key":"notify_party_if_not_consignee","label":"Notify Party (If not Consignee)"},
    {"key":"final_destination","label":"Final Destination"},
    {"key":"gross_weight_kg","label":"Weight (kg)"},
    {"key":"board_date","label":"Board Date"},
    {"key":"issuing_company","label":"Issuing Company"},
    {"key":"name_of_authorized_signatory","label":"Name of Authorized Signatory"}
  ]'::jsonb,
  true
)
ON CONFLICT (slug) DO NOTHING;
